# If not running interactively, don't do anything
[ -z "$PS1" ] && return

#PS1='[\t \h:\w]$ '
PS1='\h:\w$ '

# don't put duplicate lines in the history. See bash(1) for more options
# don't overwrite GNU Midnight Commander's setting of `ignorespace'.
export HISTCONTROL=$HISTCONTROL${HISTCONTROL+,}ignoredups
# ... or force ignoredups and ignorespace
export HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

export EDITOR="subl"
export SVN_EDITOR="vim"

#############################################
#Paths

PATH=/usr/local/bin:/opt:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin
export PATH="/Applications/Postgres.app/Contents/MacOS/bin:$PATH"
export PATH=$PATH:/usr/local/bin/git
export PATH=$PATH:/usr/local/mysql/bin
export PATH=$PATH:/opt/mongodb/bin
export PATH=$PATH:/opt/redis/src
export PATH=$PATH:/opt/phantomjs/bin
export PATH=$PATH:$HOME/development
export PATH=$PATH:$HOME/bin
### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

export NODE_PATH=/usr/local/lib/node_modules

#############################################
#Python specific settings

# VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python
export WORKON_HOME=$HOME/virtualenvs
export PIP_VIRTUALENV_BASE=$WORKON_HOME
export PIP_RESPECT_VIRTUALENV=true

if [ -f ~/.bash/virtualenvwrapper_lazy.sh ]; then
    . ~/.bash/virtualenvwrapper_lazy.sh
fi

if [ -f ~/.bash/git-completion.sh ]; then
	. ~/.bash/git-completion.sh
fi

if [ -f ~/.bash/django_bash_completion.sh ]; then
	. ~/.bash/django_bash_completion.sh
fi
